config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/articles', to: 'articles#index'

  get '/articles/new', to: 'articles#new', as: 'new_article'
  post 'articles', to: 'articles#create'

  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  patch '/articles/:id', to: 'articles#update'

  get '/articles/:id', to: 'articles#show', as: 'article'

  delete 'articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def edit
    @article = Article.find(params[:id])
  end

  # PATCH '/articles/:id'
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to @articles
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class='container'>
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content%>

    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class = 'container'>
  <h1>Edit article</h1>
  <br>
  <%= render('form') %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>
    <% @articles.each do |article| %>
      <h3><%= link_to article.title, article %> | <%= link_to 'edit', edit_article_path(article)%> | <%= link_to 'delete', article, method: "delete",  data: { confirm: "Delete #{article.title}?" }%></h3>
      <p><%= article.content%></p>
    <% end %>
</div>

app/views/articles/new.html.erb
<div class = 'container'>
  <h1>Create a new article</h1>
  <br>
  <%= render('form') %>
</div>

app/views/articles/show.html.erb
<div class='container'>
  <h1><%= @article.title %></h1>
  <p><%= @article.content %></p>
</div>
<div>
  <p class='container'><%= link_to 'Edit', edit_article_path(@article)%></p>
  <p class='container'><%= link_to '<< All Articles', articles_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>